Fix admin_dns_server variable to use interfaces[admin_dev] rather than admin_ip which no longer exists
Enter the dhcp domain you wish to use (example: example.com): |ovirt.priv| ovirt.priv
/usr/sbin/ovirt-installer:218: undefined local variable or method `admin_ip' for #<Object:0xb80d79ac> (NameError)